name: SAST Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sast:
    name: SAST Scan
    runs-on: ubuntu-latest
    
    # Определяем сервисы (аналог definitions:services в Bitbucket)
    services:
      docker:
        image: docker:20.10.7
        options: --memory="2048m"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Run SAST Scan
        run: |
          docker run -i -v "$(pwd):/app" -w /app vsyrotin/sast:0.6 /bin/sh -c "ls -l && python ../sast.py --dojo-token '${{ secrets.DOJO_TOKEN }}' --ci-commit-tag '0.0.1' --ci-project-url 'http://some.com' --ci-project-namespace '${{ github.repository }}' --ci-project-id '${{ github.repository_id }}' --ci-project-name '${{ github.repository }}'"
